name: Test Workflow

on:
  pull_request:
    paths:
      - 'README.md'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.ref_name }}

      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

      - name: Run Tests
        if: steps.PR.outputs.pr_found == 'true'
        run: echo "Running tests for PR"
