name: Test Workflow

on:
  push:
    paths:
      - 'README.md'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tests:
    runs-on: ubuntu-latest
    needs: push
    if: needs.push.outputs.pr_found == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: echo "Running tests for PR #${{ needs.push.outputs.pr_number }}"
